export const menuItems = [
  { label: "Купить", withPopover: false, popoverItems: [] },
  { label: "Продать", withPopover: false, popoverItems: [] },
  { label: "Передать клиента", withPopover: false, popoverItems: [] },
  {
    label: "Районы",
    withPopover: true,
    popoverItems: [
      "Downtown Dubai",
      "Palm Jumeirah",
      "Dubai Marina",
      "JBR",
      "Business Bay",
      "Emaar Beachfront",
      "Dubai Hills Estate",
      "Dubai Creek Harbour",
      "Все районы Дубая",
    ],
  },
  {
    label: "Проекты",
    withPopover: true,
    popoverItems: [
      "Квартиры",
      "Пентхаусы",
      "Виллы",
      "Таунхаусы",
      "Земельные участки",
      "Все проекты в Дубае",
    ],
  },
  {
    label: "Застройщики",
    withPopover: true,
    popoverItems: [
      "Emaar",
      "DAMAC",
      "Meraas",
      "Select Group",
      "Все застройщики в Дубае",
    ],
  },
  {
    label: "Услуги",
    withPopover: true,
    popoverItems: [
      "Покупка недвижимости",
      "Продажа недвижимости",
      "Аренда недвижимости",
      "Управление недвижимостью",
      "Коммерческая недвижимость",
      "Ипотека",
      "Краткосрочная аренда",
      "Юридические услуги в ОАЭ",
      "Передача имущества",
      "Недвижимость в Абу-Даби",
      "Недвижимость в Лондоне",
      "Недвижимость в Австрии",
      "Недвижимость на Кипре",
    ],
  },
  {
    label: "О компании",
    withPopover: true,
    popoverItems: [
      "Metropolitan Group",
      "Присоединяйтесь к Metropolitan",
      "Агенты",
      "Медиа",
      "Блог",
      "СМИ о нас",
      "Контакты",
    ],
  },
];
